### ISSUE TITLE
Recent incompatibilities 

### ISSUE THREAD

**Issue by moalamri** [Kiho/aspcore-spa-cli#9]
Hi,
A lot have changed with Vite 3 and svelte-cli
I used to call the backend with no issues on the same port (thanks to your proxy).
but now same port is giving error 404
I don't know if this is because the recent updates to Vite or that the proxy fails to start.
How to debug this and know the reason for giving 404 when I call the backend?

here's the output I have from the console
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TimeoutException: The svelte-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
         at SpaCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
         at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
         at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Thank you so much

**Comment by moalamri** [comment]
Fixed by adding the new configs to vite.config.js
```jsonc
      proxy: {
        '/api': {
          target: 'http://localhost:5000', // Port of backend
        }
      }
```
